name: foldflow-env
channels:
  - conda-forge
dependencies:
  # Core
  - python >=3.10,<3.11
  - pytorch<2
  - libstdcxx-ng
  - openmm
  - dm-tree
  - pip
  - pip:
      - mdtraj==1.9.7
      - biopython
      - click
      - corner
      - debugpy
      - einops
      - fair-esm
      - git+https://github.com/joeybose/geomstats.git
      - gputil
      - hydra-core
      - hydra-joblib-launcher
      - ipdb
      - lightning
      - lmdb
      - ml-collections
      - numpy
      - pandas
      - pot
      - pytest
      - tmtools
      - tqdm
      - wandb>=0.15.1
      - pydantic
      - biotite
      - -e .
