# Configuration for SDE path exploration inference
defaults:
  - base
  - override model: ff2
  - _self_

inference:
  flow:
    num_t: 50

  samples:
    inference_method: "sde_path_exploration"
    method_config:
      num_branches: 4          # Number of branches to explore
      num_keep: 2             # Number of best branches to keep
      noise_scale: 0.05       # SDE noise scale
      selector: "tm_score"    # Scoring function: "tm_score" or "rmsd"
      branch_start_time: 0.0  # When to start branching (0.0 to 1.0)
      branch_interval: 0.0    # Time interval between branches (0.0 = every timestep) 