# Configuration for inference on SE(3) diffusion experiments.
defaults:
  - base
  - override model: ff2
  - _self_

experiment:
  eval_dir: ./ # if None the evaluation won't be saved.

flow_matcher:
  so3:
    inference_scaling: 10.0

inference:
  name: null
  gpu_id: 5  # CUDA GPU to use
  seed: 123
  full_ckpt_dir: ./ckpt/baseline/

  # Directory of software, weights, and outputs.
  pt_hub_dir: ./hub/checkpoints
  pmpnn_dir: ./ProteinMPNN/
  output_dir: ./results

  # Path to model weights.
  weights_path: ./models/ff2_base.pth

  flow:
    # Number of steps.
    num_t: 50
    # Analogous to sampling temperature.
    noise_scale: 1.0
    # Final t.
    min_t: 0.01

  samples:
    # Number of backbone samples per sequence length.
    samples_per_length: 50
    # Number of ESMFdold samples per backbone sample.
    seq_per_sample: 8
    # Minimum sequence length to sample.
    min_length: 100
    # Maximum sequence length to sample.
    max_length: 300
    # gap between lengths to sample. i.e. this script will sample all lengths
    # in range(min_length, max_length, length_step)
    length_step: 50
    

    # list of methods:
    # "standard": StandardInference,
    # "best_of_n": BestOfNInference,
    # "noise_search_sde": NoiseSearchSDEInference,
    # "noise_search_divfree": NoiseSearchDivFreeInference,
    # "noise_search_divfree_max": NoiseSearchDivFreeMaxInference,
    # "sde_simple": SDESimpleInference,
    # "divfree_max_simple": DivFreeMaxSimpleInference,
    # "random_search_noise": RandomSearchNoiseInference,

    # Inference method configuration
    inference_method: "best_of_n"
    
    # Method-specific configuration
    method_config:
      selector: "geometric"  # Scoring function
      
      # Sample massaging configuration (applies to all noising methods)
      massage_steps: 0  # Number of additional inference steps to clean up noisy samples (0 to disable)

      # DivFree Max Simple configuration
      # lambda_div: 0.2  # Scale factor for divergence-free field
      # particle_repulsion_factor: 0.02  # Repulsion strength (default 0.02 of gaussian noise)
      # noise_schedule_end_factor: 0.7  # Linear noise decrease factor (1.0 -> 0.7 by end)

      num_branches: 2  # Number of branches per round
      num_keep: 1  # Number of top samples to keep each round
      num_rounds: 9  # Use all 9 rounds as intended

      # Noise Search SDE configuration
      noise_scale: 0.2  # Scale of noise for SDE
      
      # DivFree Max Noise Search configuration (when using noise_search_divfree_max)
      lambda_div: 0.3
      particle_repulsion_factor: 0
      noise_schedule_end_factor: 0.7

      # random search + noise search configuration
      noise_type: "divfree_max"
      
      # SDE Path Exploration configuration (when using sde_path_exploration)
      # num_branches: 4  # Number of branches per step
      # num_keep: 1  # Number of branches to keep
      # noise_scale: 0.05  # Scale of noise for SDE
      # branch_start_time: 0.0  # When to start branching (0.0 to 1.0)
      
      # Divergence-free ODE configuration (when using divergence_free_ode)
      # num_branches: 4
      # num_keep: 2
      # lambda_div: 0.2  # Scale factor for divergence-free field
      # branch_start_time: 0.0
    
    # Legacy configuration (for backward compatibility)
    # best_of_n: 1  # Set to >1 to enable best-of-n (overrides inference_method)