# Configuration for SDE path exploration inference
defaults:
  - inference
  - _self_

inference:
  samples:
    inference_method: "sde_path_exploration"
    method_config:
      num_branches: 4  # Number of branches per step
      num_keep: 2  # Number of branches to keep
      noise_scale: 0.05  # Scale of noise for SDE
      selector: "tm_score"  # Scoring function
      branch_start_time: 0.0  # When to start branching (0.0 to 1.0) 