# Configuration for inference on SE(3) diffusion experiments.
defaults:
  - base
  - override model: ff2
  - _self_

experiment:
  eval_dir: ./ # if None the evaluation won't be saved.

flow_matcher:
  so3:
    inference_scaling: 10.0

inference:
  name: null
  gpu_id: 1  # CUDA GPU to use
  seed: 123
  full_ckpt_dir: ./ckpt/baseline/

  # Directory of software, weights, and outputs.
  pt_hub_dir: ./hub/checkpoints
  pmpnn_dir: ./ProteinMPNN/
  output_dir: ./results

  # Path to model weights.
  # weights_path: ./ckpt/foldflow-sfm.pth # For FoldFlow-1 with stochastic flow matcher.
  weights_path: ./models/ff2_base.pth

  flow:
    # Number of steps.
    num_t: 50
    # Analogous to sampling temperature.
    noise_scale: 0.1
    # Final t.
    min_t: 0.01

  samples:
    # Number of backbone samples per sequence length.
    samples_per_length: 50
    # Number of ESMFdold samples per backbone sample.
    seq_per_sample: 8
    # Minimum sequence length to sample.
    min_length: 100
    # Maximum sequence length to sample.
    max_length: 300
    # gap between lengths to sample. i.e. this script will sample all lengths
    # in range(min_length, max_length, length_step)
    length_step: 50
    
    # Inference method configuration
    # Options: "standard", "best_of_n", "sde_path_exploration", "divergence_free_ode"
    inference_method: "standard"
    
    # Method-specific configuration
    method_config:
      # Best-of-N configuration
      n_samples: 4  # Number of samples to generate and select best from
      selector: "tm_score"  # Scoring function: "tm_score" or "rmsd"
      
      # SDE Path Exploration configuration (when using sde_path_exploration)
      # num_branches: 4  # Number of branches per step
      # num_keep: 2  # Number of branches to keep
      # noise_scale: 0.05  # Scale of noise for SDE
      # branch_start_time: 0.0  # When to start branching (0.0 to 1.0)
      
      # Divergence-free ODE configuration (when using divergence_free_ode)
      # num_branches: 4
      # num_keep: 2
      # lambda_div: 0.2  # Scale factor for divergence-free field
      # branch_start_time: 0.0
    
    # Legacy configuration (for backward compatibility)
    # best_of_n: 1  # Set to >1 to enable best-of-n (overrides inference_method)
